[2024-10-28 22:17:16,666] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2024-10-29 12:45:49,471] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-10-29 13:02:01,284] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2024-10-29 13:28:24,517] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-10-31 13:47:19,808] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-10-31 14:11:01,729] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-11-01 15:45:05,544] WARN [kafka-log-cleaner-thread-0]: Unexpected exception thrown when cleaning log Log(dir=D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0, topicId=IjYXVeVWRaqn7W7vWZNfmw, topic=tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog, partition=0, highWatermark=90, lastStableOffset=90, logStartOffset=90, logEndOffset=90). Marking its partition (tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0) as uncleanable (kafka.log.LogCleaner)
kafka.log.LogCleaningException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:427)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
Caused by: org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
Caused by: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000000.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:951)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:228)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at org.apache.kafka.storage.internals.log.LogSegment.changeFileSuffixes(LogSegment.java:667)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:919)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:917)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:917)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:289)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1526)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1922)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1438)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1544)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:424)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
	Suppressed: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000000.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000000.index.deleted: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1430)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:947)
		... 20 more
[2024-11-01 15:45:40,642] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-11-01 15:52:11,082] WARN [kafka-log-cleaner-thread-0]: Unexpected exception thrown when cleaning log Log(dir=D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0, topicId=IjYXVeVWRaqn7W7vWZNfmw, topic=tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog, partition=0, highWatermark=109, lastStableOffset=109, logStartOffset=109, logEndOffset=109). Marking its partition (tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0) as uncleanable (kafka.log.LogCleaner)
kafka.log.LogCleaningException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:427)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
Caused by: org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
Caused by: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000090.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000090.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:951)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:228)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at org.apache.kafka.storage.internals.log.LogSegment.changeFileSuffixes(LogSegment.java:667)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:919)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:917)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:917)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:289)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1526)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1922)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1438)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1544)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:424)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
	Suppressed: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000090.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000090.index.deleted: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1430)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:947)
		... 20 more
[2024-11-01 15:57:31,954] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-11-01 16:01:02,317] WARN [kafka-log-cleaner-thread-0]: Unexpected exception thrown when cleaning log Log(dir=D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0, topicId=IjYXVeVWRaqn7W7vWZNfmw, topic=tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog, partition=0, highWatermark=128, lastStableOffset=128, logStartOffset=128, logEndOffset=128). Marking its partition (tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0) as uncleanable (kafka.log.LogCleaner)
kafka.log.LogCleaningException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:427)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
Caused by: org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0 in dir D:\kafka\__manual-logs__\server-logs
Caused by: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000109.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000109.index.deleted: The process cannot access the file because it is being used by another process
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1430)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:951)
	at org.apache.kafka.storage.internals.log.AbstractIndex.renameTo(AbstractIndex.java:228)
	at org.apache.kafka.storage.internals.log.LazyIndex$IndexValue.renameTo(LazyIndex.java:122)
	at org.apache.kafka.storage.internals.log.LazyIndex.renameTo(LazyIndex.java:202)
	at org.apache.kafka.storage.internals.log.LogSegment.changeFileSuffixes(LogSegment.java:667)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:919)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:917)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:917)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:289)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1526)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1922)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1438)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1544)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1(LogCleaner.scala:424)
	at kafka.log.LogCleaner$CleanerThread.$anonfun$cleanFilthiestLog$1$adapted(LogCleaner.scala:422)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:422)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
	Suppressed: java.nio.file.FileSystemException: D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000109.index -> D:\kafka\__manual-logs__\server-logs\tumbling-OutOfOrder-App-OOO-Late-Arriving-changelog-0\00000000000000000109.index.deleted: The process cannot access the file because it is being used by another process
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
		at java.base/java.nio.file.Files.move(Files.java:1430)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:947)
		... 20 more
[2024-11-02 16:07:42,136] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-11-02 16:11:46,337] INFO Starting the log cleaner (kafka.log.LogCleaner)
